apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: {{ .Values.lbProtocol }}
    service.beta.kubernetes.io/aws-load-balancer-name: {{ .Values.lbName }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "false" 
    service.beta.kubernetes.io/aws-load-balancer-type: {{ .Values.lbType }}
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: {{ .Values.lbTargetType }}
    service.beta.kubernetes.io/aws-load-balancer-scheme: {{ .Values.lbScheme }}
  name: elasticsearch
  namespace: {{ .Values.namespace }}
  labels:
    app: wazuh-elasticsearch
spec:
  type: LoadBalancer
  ports:
  - name: es-rest
    port: 9200
    targetPort: 9200
  selector:
    app: wazuh-elasticsearch
