apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.kibana.name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: # add your cert
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.kibana.name }}
  ports:
    - name: kibana
      port: {{ .Values.kibana.service.port }}
      targetPort: {{ .Values.kibana.service.targetPort }}
