apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.workers.name }}
  namespace: {{ .Values.namespace }}
spec:
  podManagementPolicy: Parallel
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.wazuh.app }}
      node-type: worker
  serviceName: {{ .Values.workers.serviceName }}
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{ .Values.wazuh.app }}
        node-type: worker
      name: {{ .Values.workers.name }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        {{- toYaml .Values.workers.envVariables | nindent 8 }}
        image: {{ .Values.workers.image }}:{{ .Values.workers.tag }}
        imagePullPolicy: {{ .Values.workers.imagePullPolicy }}
        name: {{ .Values.wazuh.app }}
        ports:
        - containerPort: {{ .Values.wazuh.workerPort }}
          name: agents-events
          protocol: TCP
        - containerPort: {{ .Values.wazuh.clusterPort }}
          name: cluster
          protocol: TCP
        resources:
        {{- toYaml .Values.workers.resources | nindent 10 }}
        securityContext:
          capabilities:
            add:
            - SYS_CHROOT
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /wazuh-config-mount/etc/ossec.conf
          name: config
          readOnly: true
          subPath: worker.conf
        - mountPath: /etc/ssl/root-ca.pem
          name: filebeat-certs
          readOnly: true
          subPath: root-ca.pem
        - mountPath: /etc/ssl/filebeat.pem
          name: filebeat-certs
          readOnly: true
          subPath: filebeat.pem
        - mountPath: /etc/ssl/filebeat.key
          name: filebeat-certs
          readOnly: true
          subPath: filebeat-key.pem
        - mountPath: /var/ossec/api/configuration
          name: wazuh-manager-worker
          subPath: wazuh/var/ossec/api/configuration
        - mountPath: /var/ossec/etc
          name: wazuh-manager-worker
          subPath: wazuh/var/ossec/etc
        - mountPath: /var/ossec/logs
          name: wazuh-manager-worker
          subPath: wazuh/var/ossec/logs
        - mountPath: /var/ossec/queue
          name: wazuh-manager-worker
          subPath: wazuh/var/ossec/queue
        - mountPath: /var/ossec/var/multigroups
          name: wazuh-manager-worker
          subPath: wazuh/var/ossec/var/multigroups
        - mountPath: /var/ossec/integrations
          name: wazuh-manager-worker
          subPath: wazuh/var/ossec/integrations
        - mountPath: /var/ossec/active-response/bin
          name: wazuh-manager-worker
          subPath: wazuh/var/ossec/active-response/bin
        - mountPath: /var/ossec/agentless
          name: wazuh-manager-worker
          subPath: wazuh/var/ossec/agentless
        - mountPath: /var/ossec/wodles
          name: wazuh-manager-worker
          subPath: wazuh/var/ossec/wodles
        - mountPath: /etc/filebeat
          name: wazuh-manager-worker
          subPath: filebeat/etc/filebeat
        - mountPath: /var/lib/filebeat
          name: wazuh-manager-worker
          subPath: filebeat/var/lib/filebeat
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: wazuh-conf
        name: config
      - name: filebeat-certs
        secret:
          defaultMode: 420
          secretName: odfe-ssl-certs
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: wazuh-manager-worker
      namespace: {{ .Values.namespace }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: {{ .Values.storageClassName }}
      volumeMode: Filesystem
