apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.wazuh.name }}
  namespace: {{ .Values.namespace }}
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.wazuh.app }}
      node-type: master
  serviceName: {{ .Values.wazuh.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.wazuh.app }}
        node-type: master
      name: {{ .Values.wazuh.name }}
    spec:
      containers:
      - env:
        {{- toYaml .Values.wazuh.envVariables | nindent 8 }}
        image: {{ .Values.wazuh.image }}:{{ .Values.wazuh.tag }}
        imagePullPolicy: {{ .Values.wazuh.imagePullPolicy }}
        name: {{ .Values.wazuh.app }}
        ports:
        - containerPort: {{ .Values.wazuh.managerPort }}
          name: registration
          protocol: TCP
        - containerPort: {{ .Values.wazuh.clusterPort }}
          name: cluster
          protocol: TCP
        - containerPort: {{ .Values.wazuh.apiPort }}
          name: api
          protocol: TCP
        resources:
        {{- toYaml .Values.wazuh.resources | nindent 10 }}
        securityContext:
          capabilities:
            add:
            - SYS_CHROOT
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /wazuh-config-mount/etc/ossec.conf
          name: config
          readOnly: true
          subPath: master.conf
        - mountPath: /etc/ssl/root-ca.pem
          name: filebeat-certs
          readOnly: true
          subPath: root-ca.pem
        - mountPath: /etc/ssl/filebeat.pem
          name: filebeat-certs
          readOnly: true
          subPath: filebeat.pem
        - mountPath: /etc/ssl/filebeat.key
          name: filebeat-certs
          readOnly: true
          subPath: filebeat-key.pem
        - mountPath: /wazuh-config-mount/etc/authd.pass
          name: wazuh-authd-pass
          readOnly: true
          subPath: authd.pass
        - mountPath: /var/ossec/api/configuration
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/api/configuration
        - mountPath: /var/ossec/etc
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/etc
        - mountPath: /var/ossec/logs
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/logs
        - mountPath: /var/ossec/queue
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/queue
        - mountPath: /var/ossec/var/multigroups
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/var/multigroups
        - mountPath: /var/ossec/integrations
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/integrations
        - mountPath: /var/ossec/active-response/bin
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/active-response/bin
        - mountPath: /var/ossec/agentless
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/agentless
        - mountPath: /var/ossec/wodles
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/wodles
        - mountPath: /etc/filebeat
          name: wazuh-manager-master
          subPath: filebeat/etc/filebeat
        - mountPath: /var/lib/filebeat
          name: wazuh-manager-master
          subPath: filebeat/var/lib/filebeat
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: wazuh-conf
        name: config
      - name: filebeat-certs
        secret:
          defaultMode: 420
          secretName: odfe-ssl-certs
      - name: wazuh-authd-pass
        secret:
          defaultMode: 420
          secretName: wazuh-authd-pass
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: {{ .Values.wazuh.name }}
      namespace: {{ .Values.namespace }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: {{ .Values.storageClassName }}
      volumeMode: Filesystem

